### ISSUE TITLE
Cómo podríamos escribir un predicado con reemplazo sintáctico?

### ISSUE THREAD

**Issue by honi** [fedeaar/small-Lang-spec#1]
Me refiero a cuando usamos el axioma 1 de la asignación, donde se reemplaza en la post condición la variable asignada por su nuevo valor. En la teórica usan una nomenclatura con subíndice y superíndice, que es medio incómodo quizás para escribir.

Se podrá soportar esto en esta extensión? O sino quizás podrías definir alguna nomenclatura equivalente. Yo por ahora estoy escribiendo: `Q(x, y - 1)` para decir que reemplazo todas las `x` libres en `Q` por `y - 1` pero no se si es la mejor opción. Quizás podría ser `Qₓ(y - 1)`?

**Comment by fedeaar** [comment]
me  gusta la idea. Sucede que utf-8 no soporta en simultáneo superscript y subscript.  Voy a agregar igual snippets para ambos de la forma '_<char>' y '^<char>'. En tanto convensiones, personalmente prefiero una extensión de la que usa gries para setAt. ej: SetAt(S, i, 0) = (S, i:0) tal que en el contexto de una condición como la que decis sea: (Q, x:y-1). Creo que es lo suficientemente unica para que despues se pueda parsear.

**Comment by honi** [comment]
Esta piola como lo usa Gries, me parece que es bastante claro: `(Q, x : y-1)`.

También me di cuenta viendo algunos videos más del campus que no había visto que a veces directamente ni usan esta notación, pasan directo a la equivalencia ya con el reemplazo hecho, algo así:

```
{Q: x ≤ 11}
wp(x := y - 1, Q)
    ≡ def(y - 1) ∧L y - 1 ≤ 11
    ≡ y ≤ 12
```

**Comment by fedeaar** [comment]
sip es verdad. Depende qué tanto se saltea entre pasos. De todas formas, acabo de subir una versión con los snippets para sub y superscript asique marco como resuelto. Notación = _(char) o sub(char) para subscript y ^(char) o sup(char) para super. Por temas que no entiendo el super de numeros solo funciona con sup<numero> y por temas de unicode, no toda letra tiene representación. Cualquier cosa estamos al habla, saludos!
