### ISSUE TITLE
Cierre del if en small lang

### ISSUE THREAD

**Issue by honi** [fedeaar/small-Lang-spec#2]
Me parece que los if en small lang se cierran con `endif`, y `fi` es para el lenguaje de especificación.

Si efectivamente es así, entiendo que habría que actualizarlo [acá](https://github.com/fedeaar/small-Lang-spec/blob/0c0aa4d60062e926118a2e7efa55297d5181743a/syntaxes/grammar.json#L37) para que marque con color `endif` en vez de `fi`.

**Comment by fedeaar** [comment]
Si! ahi mismo sería. Lo agrego a las reglas. Igual, por ahora voy a dejar ambos hasta que desarrolle una forma para distinguir entre los contextos
